### ISSUE TITLE
现在还不支持对象数组吗

### ISSUE THREAD

**Issue by null64** [lison16/vue-bigdata-table#3]

**Comment by lison16** [comment]
现在是只能使用二维数组的形式，后面会考虑尽可能支持两种方式

**Comment by null64** [comment]
我初略的看了下代码，只需要在item-table中修改部分代码即可，但是你其他的功能估计会受点影响，我主要是展示，所以，自己将就的用，还行，非常感谢你提供的开源，省了我不少时间 @lison16
